// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.beebeeb_uniffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_beebeeb_uniffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_beebeeb_uniffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "beebeeb_uniffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "beebeeb_uniffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_beebeeb_uniffi_checksum_func_compute_recovery_check(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_decrypt_chunk(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_decrypt_metadata(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_derive_file_key(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_derive_master_key(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_derive_share_key(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_derive_x25519_private(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_derive_x25519_public(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_encrypt_chunk(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_encrypt_metadata(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_generate_recovery_phrase(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_opaque_login_finish(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_opaque_login_start(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_opaque_registration_finish(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_opaque_registration_start(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_recover_from_phrase(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_func_x25519_shared_secret(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_chunk(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_metadata(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_chunk(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_metadata(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_compute_recovery_check(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_file_key(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_x25519_private(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_export_for_keychain(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_keychain_bytes(
    ): Short
    external fun uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_recovery_phrase(
    ): Short
    external fun ffi_beebeeb_uniffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "beebeeb_uniffi"))
        
    }
    external fun uniffi_beebeeb_uniffi_fn_clone_filekeyhandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_beebeeb_uniffi_fn_free_filekeyhandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_chunk(`ptr`: Long,`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_metadata(`ptr`: Long,`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_chunk(`ptr`: Long,`plaintext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_metadata(`ptr`: Long,`metadata`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_clone_masterkeyhandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_beebeeb_uniffi_fn_free_masterkeyhandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_keychain_bytes(`bytes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_recovery_phrase(`phrase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_compute_recovery_check(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_file_key(`ptr`: Long,`fileId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_x25519_private(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_export_for_keychain(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_compute_recovery_check(`masterKey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_decrypt_chunk(`key`: RustBuffer.ByValue,`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_decrypt_metadata(`key`: RustBuffer.ByValue,`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_derive_file_key(`masterKey`: RustBuffer.ByValue,`fileId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_derive_master_key(`password`: RustBuffer.ByValue,`salt`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_derive_share_key(`sharedSecret`: RustBuffer.ByValue,`fileId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_derive_x25519_private(`masterKey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_derive_x25519_public(`privateKey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_encrypt_chunk(`key`: RustBuffer.ByValue,`plaintext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_encrypt_metadata(`key`: RustBuffer.ByValue,`metadata`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_generate_recovery_phrase(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_opaque_login_finish(`clientState`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`serverResponse`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_opaque_login_start(`password`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_opaque_registration_finish(`clientState`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`serverResponse`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_opaque_registration_start(`password`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_recover_from_phrase(`phrase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_beebeeb_uniffi_fn_func_x25519_shared_secret(`myPrivate`: RustBuffer.ByValue,`theirPublic`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_beebeeb_uniffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_beebeeb_uniffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_beebeeb_uniffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun ffi_beebeeb_uniffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_beebeeb_uniffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_u8(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_u8(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_beebeeb_uniffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_i8(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_i8(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_beebeeb_uniffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_u16(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_u16(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_beebeeb_uniffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_i16(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_i16(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_beebeeb_uniffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_u32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_u32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_beebeeb_uniffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_i32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_i32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_beebeeb_uniffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_u64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_u64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_beebeeb_uniffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_i64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_i64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_beebeeb_uniffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_f32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_f32(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
external fun ffi_beebeeb_uniffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_f64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_f64(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
external fun ffi_beebeeb_uniffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_rust_buffer(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_beebeeb_uniffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_cancel_void(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_free_void(`handle`: Long,
): Unit
external fun ffi_beebeeb_uniffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

    
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_beebeeb_uniffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_beebeeb_uniffi_checksum_func_compute_recovery_check() != 28278.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_decrypt_chunk() != 1418.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_decrypt_metadata() != 59510.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_derive_file_key() != 7047.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_derive_master_key() != 58065.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_derive_share_key() != 10175.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_derive_x25519_private() != 64443.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_derive_x25519_public() != 3860.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_encrypt_chunk() != 23692.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_encrypt_metadata() != 360.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_generate_recovery_phrase() != 56821.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_opaque_login_finish() != 15751.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_opaque_login_start() != 19878.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_opaque_registration_finish() != 42222.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_opaque_registration_start() != 35428.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_recover_from_phrase() != 25900.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_func_x25519_shared_secret() != 52845.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_chunk() != 50441.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_metadata() != 41867.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_chunk() != 10384.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_metadata() != 60336.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_compute_recovery_check() != 4155.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_file_key() != 1679.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_x25519_private() != 61634.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_export_for_keychain() != 50366.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_keychain_bytes() != 25584.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_recovery_phrase() != 63639.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * Opaque handle to a FileKey. Created via `MasterKeyHandle::derive_file_key`.
 */
public interface FileKeyHandleInterface {
    
    fun `decryptChunk`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.ByteArray
    
    fun `decryptMetadata`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.String
    
    fun `encryptChunk`(`plaintext`: kotlin.ByteArray): EncryptedData
    
    fun `encryptMetadata`(`metadata`: kotlin.String): EncryptedData
    
    companion object
}

/**
 * Opaque handle to a FileKey. Created via `MasterKeyHandle::derive_file_key`.
 */
open class FileKeyHandle: Disposable, AutoCloseable, FileKeyHandleInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_beebeeb_uniffi_fn_free_filekeyhandle(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_beebeeb_uniffi_fn_clone_filekeyhandle(handle, status)
        }
    }

    
    @Throws(CryptoException::class)override fun `decryptChunk`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_chunk(
        it,
        FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),_status)
}
    }
    )
    }
    

    
    @Throws(CryptoException::class)override fun `decryptMetadata`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_metadata(
        it,
        FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),_status)
}
    }
    )
    }
    

    
    @Throws(CryptoException::class)override fun `encryptChunk`(`plaintext`: kotlin.ByteArray): EncryptedData {
            return FfiConverterTypeEncryptedData.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_chunk(
        it,
        FfiConverterByteArray.lower(`plaintext`),_status)
}
    }
    )
    }
    

    
    @Throws(CryptoException::class)override fun `encryptMetadata`(`metadata`: kotlin.String): EncryptedData {
            return FfiConverterTypeEncryptedData.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_metadata(
        it,
        FfiConverterString.lower(`metadata`),_status)
}
    }
    )
    }
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}


/**
 * @suppress
 */
public object FfiConverterTypeFileKeyHandle: FfiConverter<FileKeyHandle, Long> {
    override fun lower(value: FileKeyHandle): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): FileKeyHandle {
        return FileKeyHandle(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): FileKeyHandle {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: FileKeyHandle) = 8UL

    override fun write(value: FileKeyHandle, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * Opaque handle to a MasterKey. The key bytes never leave Rust except via
 * `export_for_keychain`, which is only called once to persist to the OS keychain.
 */
public interface MasterKeyHandleInterface {
    
    /**
     * Compute the recovery-check value (stored server-side to verify the phrase).
     */
    fun `computeRecoveryCheck`(): kotlin.ByteArray
    
    /**
     * Derive a FileKeyHandle for the given file ID.
     */
    fun `deriveFileKey`(`fileId`: kotlin.ByteArray): FileKeyHandle
    
    /**
     * Derive the X25519 secret scalar from the master key. Returns 32 bytes.
     */
    fun `deriveX25519Private`(): kotlin.ByteArray
    
    /**
     * Export the raw 32-byte key for writing to the OS keychain.
     * Only call this once at account setup; never log or transmit the result.
     */
    fun `exportForKeychain`(): kotlin.ByteArray
    
    companion object
}

/**
 * Opaque handle to a MasterKey. The key bytes never leave Rust except via
 * `export_for_keychain`, which is only called once to persist to the OS keychain.
 */
open class MasterKeyHandle: Disposable, AutoCloseable, MasterKeyHandleInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_beebeeb_uniffi_fn_free_masterkeyhandle(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_beebeeb_uniffi_fn_clone_masterkeyhandle(handle, status)
        }
    }

    
    /**
     * Compute the recovery-check value (stored server-side to verify the phrase).
     */
    @Throws(CryptoException::class)override fun `computeRecoveryCheck`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_compute_recovery_check(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Derive a FileKeyHandle for the given file ID.
     */
    @Throws(CryptoException::class)override fun `deriveFileKey`(`fileId`: kotlin.ByteArray): FileKeyHandle {
            return FfiConverterTypeFileKeyHandle.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_file_key(
        it,
        FfiConverterByteArray.lower(`fileId`),_status)
}
    }
    )
    }
    

    
    /**
     * Derive the X25519 secret scalar from the master key. Returns 32 bytes.
     */
    @Throws(CryptoException::class)override fun `deriveX25519Private`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_x25519_private(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Export the raw 32-byte key for writing to the OS keychain.
     * Only call this once at account setup; never log or transmit the result.
     */
    @Throws(CryptoException::class)override fun `exportForKeychain`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_export_for_keychain(
        it,
        _status)
}
    }
    )
    }
    

    

    


    
    companion object {
        
    /**
     * Reconstruct a MasterKeyHandle from 32 raw bytes read from the OS keychain.
     */
    @Throws(CryptoException::class) fun `fromKeychainBytes`(`bytes`: kotlin.ByteArray): MasterKeyHandle {
            return FfiConverterTypeMasterKeyHandle.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_keychain_bytes(
    
        FfiConverterByteArray.lower(`bytes`),_status)
}
    )
    }
    

        
    /**
     * Reconstruct a MasterKeyHandle from a 12-word BIP39 recovery phrase.
     */
    @Throws(CryptoException::class) fun `fromRecoveryPhrase`(`phrase`: kotlin.String): MasterKeyHandle {
            return FfiConverterTypeMasterKeyHandle.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_recovery_phrase(
    
        FfiConverterString.lower(`phrase`),_status)
}
    )
    }
    

        
    }
    
}


/**
 * @suppress
 */
public object FfiConverterTypeMasterKeyHandle: FfiConverter<MasterKeyHandle, Long> {
    override fun lower(value: MasterKeyHandle): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): MasterKeyHandle {
        return MasterKeyHandle(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): MasterKeyHandle {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: MasterKeyHandle) = 8UL

    override fun write(value: MasterKeyHandle, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * Result of encrypting a chunk or metadata. Contains the cipher suite
 * identifier, a random nonce, and the ciphertext (including the GCM tag).
 */
data class EncryptedData (
    var `cipherSuite`: kotlin.String
    , 
    var `nonce`: kotlin.ByteArray
    , 
    var `ciphertext`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEncryptedData: FfiConverterRustBuffer<EncryptedData> {
    override fun read(buf: ByteBuffer): EncryptedData {
        return EncryptedData(
            FfiConverterString.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: EncryptedData) = (
            FfiConverterString.allocationSize(value.`cipherSuite`) +
            FfiConverterByteArray.allocationSize(value.`nonce`) +
            FfiConverterByteArray.allocationSize(value.`ciphertext`)
    )

    override fun write(value: EncryptedData, buf: ByteBuffer) {
            FfiConverterString.write(value.`cipherSuite`, buf)
            FfiConverterByteArray.write(value.`nonce`, buf)
            FfiConverterByteArray.write(value.`ciphertext`, buf)
    }
}



/**
 * Master key bytes returned from `derive_master_key`.
 */
data class MasterKeyResult (
    var `key`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMasterKeyResult: FfiConverterRustBuffer<MasterKeyResult> {
    override fun read(buf: ByteBuffer): MasterKeyResult {
        return MasterKeyResult(
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: MasterKeyResult) = (
            FfiConverterByteArray.allocationSize(value.`key`)
    )

    override fun write(value: MasterKeyResult, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`key`, buf)
    }
}



/**
 * Result of finishing an OPAQUE client login.
 */
data class OpaqueLoginFinishResult (
    var `message`: kotlin.ByteArray
    , 
    var `sessionKey`: kotlin.ByteArray
    , 
    var `exportKey`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOpaqueLoginFinishResult: FfiConverterRustBuffer<OpaqueLoginFinishResult> {
    override fun read(buf: ByteBuffer): OpaqueLoginFinishResult {
        return OpaqueLoginFinishResult(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: OpaqueLoginFinishResult) = (
            FfiConverterByteArray.allocationSize(value.`message`) +
            FfiConverterByteArray.allocationSize(value.`sessionKey`) +
            FfiConverterByteArray.allocationSize(value.`exportKey`)
    )

    override fun write(value: OpaqueLoginFinishResult, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`message`, buf)
            FfiConverterByteArray.write(value.`sessionKey`, buf)
            FfiConverterByteArray.write(value.`exportKey`, buf)
    }
}



/**
 * Result of starting an OPAQUE registration or login.
 */
data class OpaqueStartResult (
    var `message`: kotlin.ByteArray
    , 
    var `state`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOpaqueStartResult: FfiConverterRustBuffer<OpaqueStartResult> {
    override fun read(buf: ByteBuffer): OpaqueStartResult {
        return OpaqueStartResult(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: OpaqueStartResult) = (
            FfiConverterByteArray.allocationSize(value.`message`) +
            FfiConverterByteArray.allocationSize(value.`state`)
    )

    override fun write(value: OpaqueStartResult, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`message`, buf)
            FfiConverterByteArray.write(value.`state`, buf)
    }
}



/**
 * Result of generating a recovery phrase.
 */
data class RecoveryPhraseResult (
    var `phrase`: kotlin.String
    , 
    var `masterKey`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRecoveryPhraseResult: FfiConverterRustBuffer<RecoveryPhraseResult> {
    override fun read(buf: ByteBuffer): RecoveryPhraseResult {
        return RecoveryPhraseResult(
            FfiConverterString.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: RecoveryPhraseResult) = (
            FfiConverterString.allocationSize(value.`phrase`) +
            FfiConverterByteArray.allocationSize(value.`masterKey`)
    )

    override fun write(value: RecoveryPhraseResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`phrase`, buf)
            FfiConverterByteArray.write(value.`masterKey`, buf)
    }
}





sealed class CryptoException: kotlin.Exception() {
    
    class Encryption(
        
        val `detail`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "detail=${ `detail` }"
    }
    
    class Decryption(
        ) : CryptoException() {
        override val message
            get() = ""
    }
    
    class Kdf(
        
        val `detail`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "detail=${ `detail` }"
    }
    
    class InvalidRecoveryPhrase(
        ) : CryptoException() {
        override val message
            get() = ""
    }
    
    class InvalidInput(
        
        val `detail`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "detail=${ `detail` }"
    }
    
    class Opaque(
        
        val `detail`: kotlin.String
        ) : CryptoException() {
        override val message
            get() = "detail=${ `detail` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CryptoException> {
        override fun lift(error_buf: RustBuffer.ByValue): CryptoException = FfiConverterTypeCryptoError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCryptoError : FfiConverterRustBuffer<CryptoException> {
    override fun read(buf: ByteBuffer): CryptoException {
        

        return when(buf.getInt()) {
            1 -> CryptoException.Encryption(
                FfiConverterString.read(buf),
                )
            2 -> CryptoException.Decryption()
            3 -> CryptoException.Kdf(
                FfiConverterString.read(buf),
                )
            4 -> CryptoException.InvalidRecoveryPhrase()
            5 -> CryptoException.InvalidInput(
                FfiConverterString.read(buf),
                )
            6 -> CryptoException.Opaque(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CryptoException): ULong {
        return when(value) {
            is CryptoException.Encryption -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`detail`)
            )
            is CryptoException.Decryption -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CryptoException.Kdf -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`detail`)
            )
            is CryptoException.InvalidRecoveryPhrase -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CryptoException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`detail`)
            )
            is CryptoException.Opaque -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`detail`)
            )
        }
    }

    override fun write(value: CryptoException, buf: ByteBuffer) {
        when(value) {
            is CryptoException.Encryption -> {
                buf.putInt(1)
                FfiConverterString.write(value.`detail`, buf)
                Unit
            }
            is CryptoException.Decryption -> {
                buf.putInt(2)
                Unit
            }
            is CryptoException.Kdf -> {
                buf.putInt(3)
                FfiConverterString.write(value.`detail`, buf)
                Unit
            }
            is CryptoException.InvalidRecoveryPhrase -> {
                buf.putInt(4)
                Unit
            }
            is CryptoException.InvalidInput -> {
                buf.putInt(5)
                FfiConverterString.write(value.`detail`, buf)
                Unit
            }
            is CryptoException.Opaque -> {
                buf.putInt(6)
                FfiConverterString.write(value.`detail`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}
        /**
         * Compute a recovery check value from a master key. Returns 32-byte check value.
         * This is stored server-side so we can verify a recovery phrase produces the
         * correct master key.
         */
    @Throws(CryptoException::class) fun `computeRecoveryCheck`(`masterKey`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_compute_recovery_check(
    
        FfiConverterByteArray.lower(`masterKey`),_status)
}
    )
    }
    

        /**
         * Decrypt a ciphertext chunk that was produced by `encrypt_chunk`.
         */
    @Throws(CryptoException::class) fun `decryptChunk`(`key`: kotlin.ByteArray, `nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_decrypt_chunk(
    
        FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),_status)
}
    )
    }
    

        /**
         * Decrypt a metadata blob back to a UTF-8 string.
         */
    @Throws(CryptoException::class) fun `decryptMetadata`(`key`: kotlin.ByteArray, `nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_decrypt_metadata(
    
        FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),_status)
}
    )
    }
    

        /**
         * Derive a per-file encryption key from a master key and file ID via
         * HKDF-SHA256. Returns the 32-byte file key.
         */
    @Throws(CryptoException::class) fun `deriveFileKey`(`masterKey`: kotlin.ByteArray, `fileId`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_derive_file_key(
    
        FfiConverterByteArray.lower(`masterKey`),FfiConverterByteArray.lower(`fileId`),_status)
}
    )
    }
    

        /**
         * Derive a 32-byte master key from a password and salt (>= 16 bytes) via
         * Argon2id. Returns the key bytes.
         */
    @Throws(CryptoException::class) fun `deriveMasterKey`(`password`: kotlin.String, `salt`: kotlin.ByteArray): MasterKeyResult {
            return FfiConverterTypeMasterKeyResult.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_derive_master_key(
    
        FfiConverterString.lower(`password`),FfiConverterByteArray.lower(`salt`),_status)
}
    )
    }
    

        /**
         * Derive a share key from a shared secret and file ID. Returns 32-byte share key.
         */
    @Throws(CryptoException::class) fun `deriveShareKey`(`sharedSecret`: kotlin.ByteArray, `fileId`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_derive_share_key(
    
        FfiConverterByteArray.lower(`sharedSecret`),FfiConverterByteArray.lower(`fileId`),_status)
}
    )
    }
    

        /**
         * Derive an X25519 secret scalar from a master key. Returns 32 bytes.
         */
    @Throws(CryptoException::class) fun `deriveX25519Private`(`masterKey`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_derive_x25519_private(
    
        FfiConverterByteArray.lower(`masterKey`),_status)
}
    )
    }
    

        /**
         * Derive an X25519 public point from a secret scalar. Returns 32 bytes.
         */
    @Throws(CryptoException::class) fun `deriveX25519Public`(`privateKey`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_derive_x25519_public(
    
        FfiConverterByteArray.lower(`privateKey`),_status)
}
    )
    }
    

        /**
         * Encrypt a plaintext chunk with AES-256-GCM. Returns the encrypted data
         * containing cipher suite, nonce, and ciphertext.
         */
    @Throws(CryptoException::class) fun `encryptChunk`(`key`: kotlin.ByteArray, `plaintext`: kotlin.ByteArray): EncryptedData {
            return FfiConverterTypeEncryptedData.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_encrypt_chunk(
    
        FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`plaintext`),_status)
}
    )
    }
    

        /**
         * Encrypt a UTF-8 metadata string (filename, path, etc.) with AES-256-GCM.
         */
    @Throws(CryptoException::class) fun `encryptMetadata`(`key`: kotlin.ByteArray, `metadata`: kotlin.String): EncryptedData {
            return FfiConverterTypeEncryptedData.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_encrypt_metadata(
    
        FfiConverterByteArray.lower(`key`),FfiConverterString.lower(`metadata`),_status)
}
    )
    }
    

        /**
         * Generate a new 12-word BIP39 recovery phrase and the corresponding master
         * key. The phrase IS the master secret.
         */
    @Throws(CryptoException::class) fun `generateRecoveryPhrase`(): RecoveryPhraseResult {
            return FfiConverterTypeRecoveryPhraseResult.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_generate_recovery_phrase(
    
        _status)
}
    )
    }
    

        /**
         * Finish OPAQUE client login. Returns the finalization message, the session
         * key, and the export key (used to derive the master key envelope).
         */
    @Throws(CryptoException::class) fun `opaqueLoginFinish`(`clientState`: kotlin.ByteArray, `password`: kotlin.ByteArray, `serverResponse`: kotlin.ByteArray): OpaqueLoginFinishResult {
            return FfiConverterTypeOpaqueLoginFinishResult.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_opaque_login_finish(
    
        FfiConverterByteArray.lower(`clientState`),FfiConverterByteArray.lower(`password`),FfiConverterByteArray.lower(`serverResponse`),_status)
}
    )
    }
    

        /**
         * Start OPAQUE client login. Returns the login message and client state.
         */
    @Throws(CryptoException::class) fun `opaqueLoginStart`(`password`: kotlin.ByteArray): OpaqueStartResult {
            return FfiConverterTypeOpaqueStartResult.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_opaque_login_start(
    
        FfiConverterByteArray.lower(`password`),_status)
}
    )
    }
    

        /**
         * Finish OPAQUE client registration. Takes the client state from the start
         * step, the password, and the server's response. Returns the registration
         * upload bytes to send to the server.
         */
    @Throws(CryptoException::class) fun `opaqueRegistrationFinish`(`clientState`: kotlin.ByteArray, `password`: kotlin.ByteArray, `serverResponse`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_opaque_registration_finish(
    
        FfiConverterByteArray.lower(`clientState`),FfiConverterByteArray.lower(`password`),FfiConverterByteArray.lower(`serverResponse`),_status)
}
    )
    }
    

        /**
         * Start OPAQUE client registration. Returns the registration message and
         * client state (both needed for the finish step).
         */
    @Throws(CryptoException::class) fun `opaqueRegistrationStart`(`password`: kotlin.ByteArray): OpaqueStartResult {
            return FfiConverterTypeOpaqueStartResult.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_opaque_registration_start(
    
        FfiConverterByteArray.lower(`password`),_status)
}
    )
    }
    

        /**
         * Recover a master key from a 12-word BIP39 recovery phrase.
         * Returns the 32-byte master key.
         */
    @Throws(CryptoException::class) fun `recoverFromPhrase`(`phrase`: kotlin.String): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_recover_from_phrase(
    
        FfiConverterString.lower(`phrase`),_status)
}
    )
    }
    

        /**
         * Compute an X25519 shared secret from my secret scalar and their public point.
         * Returns 32-byte shared secret.
         */
    @Throws(CryptoException::class) fun `x25519SharedSecret`(`myPrivate`: kotlin.ByteArray, `theirPublic`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.uniffi_beebeeb_uniffi_fn_func_x25519_shared_secret(
    
        FfiConverterByteArray.lower(`myPrivate`),FfiConverterByteArray.lower(`theirPublic`),_status)
}
    )
    }
    


