pub mod archive;
pub mod blob;
pub mod chunk_stream;
pub mod cli_auth;
pub mod constellation;
pub mod encrypt;
pub mod error;
pub mod file_encrypt;
pub mod file_request;
// rusqlite-backed; native targets only so beebeeb-wasm builds in place (0653).
#[cfg(not(target_arch = "wasm32"))]
pub mod fp_cache;
pub mod hash;
pub mod kdf;
pub mod media;
pub mod metadata_wire;
pub mod opaque;
pub mod opaque_protocol;
pub mod pdf;
pub mod recovery;
pub mod search_index;
pub mod search_sync;
pub mod share_token;
pub mod sync;
pub mod thumbnail;
pub mod transfer;
pub mod zip;

pub use error::CoreError;
